// examples/react/src/App.tsx
import { useState } from "react";
import "./App.css";
import { Editor } from "@rockerrishabh/rich-text-editor-react";

function App() {
  const [content, setContent] = useState("");

  return (
    <div className="app-root">
      <h1>Rich Text Editor — React Example</h1>
      <Editor
        className="rte-editor"
        initialContent="<p>Hello from the local example!</p>"
        placeholder="Start typing..."
        onChange={(c: string) => setContent(c)}
      />

      <section className="output">
        <h2>Editor Output</h2>
        <pre>{content}</pre>
      </section>
    </div>
  );
}

export default App;

// examples/solid/src/App.tsx
import { createSignal } from "solid-js";
import { Editor } from "@rockerrishabh/rich-text-editor-solid";

function App() {
  const [content, setContent] = createSignal("");

  return (
    <div>
      <h1>Solid JS Rich Text Editor</h1>
      <Editor
        initialContent="<p>Hello from Solid!</p>"
        onChange={(html) => setContent(html)}
      />
      <hr />
      <h2>Output:</h2>
      <div innerHTML={content()} />
    </div>
  );
}

export default App;
